import {
  Camera,
  Smartphone,
  Wifi,
  Lock,
  Database,
  Headphones,
  Zap,
  Globe,
  Shield,
  Settings,
  Server,
  FileText,
  Tv,
  Satellite,
} from 'lucide-react'

export const products = [
  {
    id: 1,
    title: 'CCTV Camera Systems',
    description: 'High-definition surveillance systems with night vision and remote monitoring capabilities',
    icon: Camera,
    price: 'Custom Quote',
    image: '/products/cctv.jpg',
  },
  {
    id: 2,
    title: 'Biometric Access Control',
    description: 'Advanced fingerprint and facial recognition systems for secure facility access',
    icon: Lock,
    price: 'Custom Quote',
    image: '/products/biometric.jpg',
  },
  {
    id: 3,
    title: 'IP Telephone Systems',
    description: 'Modern VoIP solutions for seamless business communication',
    icon: Headphones,
    price: 'Custom Quote',
    image: '/products/telephone.jpg',
  },
  {
    id: 4,
    title: 'Server Infrastructure',
    description: 'Reliable server solutions for enterprise-grade data management',
    icon: Server,
    price: 'Custom Quote',
    image: '/products/server.jpg',
  },
  {
    id: 5,
    title: 'Network Installation',
    description: 'Structured cabling and network infrastructure setup',
    icon: Wifi,
    price: 'Custom Quote',
    image: '/products/network.jpg',
  },
  {
    id: 6,
    title: 'Office IT Equipment',
    description: 'Complete workstation and peripherals supply for your office',
    icon: Smartphone,
    price: 'Custom Quote',
    image: '/products/office.jpg',
  },
  {
    id: 7,
    title: 'Power Management Systems',
    description: 'UPS and backup power solutions for continuous operation',
    icon: Zap,
    price: 'Custom Quote',
    image: '/products/power.jpg',
  },
  {
    id: 8,
    title: 'Cloud Solutions',
    description: 'Secure cloud infrastructure and data backup services',
    icon: Globe,
    price: 'Custom Quote',
    image: '/products/cloud.jpg',
  },
  {
    id: 9,
    title: 'Security Compliance',
    description: 'ISO certifications and security audits for regulatory compliance',
    icon: Shield,
    price: 'Custom Quote',
    image: '/products/cctv.jpg',
  },
  {
    id: 10,
    title: 'System Configuration',
    description: 'Professional setup and optimization of all IT systems',
    icon: Settings,
    price: 'Custom Quote',
    image: '/products/system.jpg',
  },
  {
    id: 11,
    title: 'Data Storage Solutions',
    description: 'NAS and SAN solutions for efficient data management',
    icon: Database,
    price: 'Custom Quote',
    image: '/products/data.jpg',
  },
  {
    id: 12,
    title: 'Documentation & Support',
    description: 'Comprehensive system documentation and ongoing technical support',
    icon: FileText,
    price: 'Custom Quote',
    image: '/products/documentation.jpg',
  },
  {
    id: 13,
    title: 'DSTV Installation',
    description: 'Professional DSTV installation and setup services',
    icon: Tv,
    price: 'Custom Quote',
    image: '/products/dstv.jpg',
  },
  {
    id: 14,
    title: 'Satellite TV',
    description: 'Complete satellite TV solutions and installations',
    icon: Satellite,
    price: 'Custom Quote',
    image: '/products/satelitte.jpg',
  },
]
