import { Camera, Lock, Phone, Monitor, Network, Server, Zap, Cloud, Shield, Settings, Database, FileText, Tv, Satellite } from 'lucide-react'

export interface Service {
  id: string
  title: string
  description: string
  icon: any
  slug: string
  details: string
  features: string[]
  benefits: string[]
  image: string
}

export const services: Service[] = [
  {
    id: '1',
    title: 'CCTV Camera Systems',
    description: 'High-definition surveillance systems with night vision and remote monitoring capabilities.',
    icon: Camera,
    slug: 'cctv',
    details: 'Our CCTV systems provide HD and 4K video surveillance with advanced features like night vision, motion detection, and cloud storage. We supply industry-leading brands and handle complete installation, configuration, and maintenance.',
    features: [
      'HD and 4K resolution options',
      'Night vision and infrared technology',
      'Motion detection and alerts',
      'Cloud and local storage',
      '24/7 monitoring capabilities',
      'Professional installation included',
    ],
    benefits: [
      'Deter criminal activity',
      'Monitor multiple locations remotely',
      'Evidence documentation',
      'Peace of mind for business',
      'Insurance premium reductions',
      'Scalable solutions',
    ],
    image: '/services/cctv.jpg',
  },
  {
    id: '2',
    title: 'Biometric Access Control',
    description: 'Advanced fingerprint and facial recognition systems for secure facility access.',
    icon: Lock,
    slug: 'biometrics',
    details: 'Secure your facilities with biometric access control systems featuring fingerprint recognition, facial recognition, and multi-factor authentication. Perfect for offices, data centers, and sensitive areas.',
    features: [
      'Fingerprint recognition',
      'Facial recognition technology',
      'Card and PIN options',
      'Multi-factor authentication',
      'Real-time access logs',
      'Integration with security systems',
    ],
    benefits: [
      'Eliminate lost key cards and PINs',
      'Unauthorized access prevention',
      'Detailed access audit trails',
      'Fast and seamless entry',
      'Flexible permission management',
      'Enhanced workplace security',
    ],
    image: '/services/biometric.jpg',
  },
  {
    id: '3',
    title: 'IP Telephone Systems',
    description: 'Modern VoIP solutions for seamless business communication.',
    icon: Phone,
    slug: 'ip-phones',
    details: 'Replace traditional PBX systems with cost-effective IP telephone solutions. Our systems support unlimited extensions, advanced call routing, voicemail integration, and mobile integration.',
    features: [
      'VoIP technology',
      'Unlimited extensions',
      'Advanced call routing',
      'Integrated voicemail',
      'Conference calling',
      'Mobile app integration',
    ],
    benefits: [
      'Reduce communication costs',
      'Flexible remote work support',
      'Professional communication',
      'Easy scalability',
      'Advanced features included',
      'Unified communications',
    ],
    image: '/services/telephone.jpg',
  },
  {
    id: '4',
    title: 'Server Infrastructure',
    description: 'Reliable server solutions for enterprise-grade data management.',
    icon: Server,
    slug: 'server-infrastructure',
    details: 'Enterprise-grade server solutions designed for optimal performance, reliability, and scalability. We provide complete server setup, configuration, and ongoing maintenance.',
    features: [
      'High-performance servers',
      'Redundant power supplies',
      'RAID storage configurations',
      'Remote management',
      '24/7 monitoring',
      'Disaster recovery options',
    ],
    benefits: [
      'Maximum uptime and reliability',
      'Scalable computing power',
      'Data security and protection',
      'Cost-effective solutions',
      'Professional maintenance',
      'Future-ready infrastructure',
    ],
    image: '/services/server.jpg',
  },
  {
    id: '5',
    title: 'Network Installation',
    description: 'Structured cabling and network infrastructure setup.',
    icon: Network,
    slug: 'networks',
    details: 'Complete structured network installation with CAT6/CAT6A cabling, fiber optics, and enterprise-grade equipment. We design and implement networks that scale with your business.',
    features: [
      'CAT6 and CAT6A cabling',
      'Fiber optic solutions',
      'Network switches and routers',
      'WiFi infrastructure',
      'Network security',
      'Documentation and testing',
    ],
    benefits: [
      'High-speed connectivity',
      'Future-ready infrastructure',
      'Minimal interference',
      'Professional testing',
      'Scalable design',
      'Enterprise reliability',
    ],
    image: '/services/network.jpg',
  },
  {
    id: '6',
    title: 'Office IT Equipment',
    description: 'Complete workstation and peripherals supply for your office.',
    icon: Monitor,
    slug: 'it-equipment',
    details: 'We provide comprehensive supply of office IT equipment including computers, printers, networking hardware, and peripherals. Full technical support and maintenance included.',
    features: [
      'Latest computer systems',
      'Multifunction printers',
      'Networking equipment',
      'Peripherals and accessories',
      'Technical warranty',
      'On-site support',
    ],
    benefits: [
      'Enterprise-grade equipment',
      'Competitive pricing',
      'Prompt delivery and setup',
      'Technical support included',
      'Minimal downtime',
      'Future-proof solutions',
    ],
    image: '/services/office.jpg',
  },
  {
    id: '7',
    title: 'Power Management Systems',
    description: 'UPS and backup power solutions for continuous operation.',
    icon: Zap,
    slug: 'power-management',
    details: 'Ensure uninterrupted power supply with our comprehensive UPS and backup power solutions. Protect your critical systems from power outages and electrical disturbances.',
    features: [
      'Uninterruptible Power Supplies (UPS)',
      'Backup generators',
      'Power conditioning',
      'Automatic voltage regulation',
      'Battery backup systems',
      'Power monitoring software',
    ],
    benefits: [
      'Zero downtime protection',
      'Data integrity preservation',
      'Equipment protection',
      'Cost savings on repairs',
      'Extended equipment lifespan',
      'Peace of mind operation',
    ],
    image: '/services/power.jpg',
  },
  {
    id: '8',
    title: 'Cloud Solutions',
    description: 'Secure cloud infrastructure and data backup services.',
    icon: Cloud,
    slug: 'cloud-solutions',
    details: 'Comprehensive cloud solutions including infrastructure setup, data migration, backup services, and cloud security. Migrate to the cloud with confidence.',
    features: [
      'Cloud infrastructure setup',
      'Data migration services',
      'Automated backups',
      'Cloud security',
      'Scalable storage',
      'Disaster recovery',
    ],
    benefits: [
      'Cost-effective scalability',
      'Anywhere access',
      'Enhanced security',
      'Automatic backups',
      'Reduced IT overhead',
      'Business continuity',
    ],
    image: '/services/cloud.jpg',
  },
  {
    id: '9',
    title: 'Security Compliance',
    description: 'ISO certifications and security audits for regulatory compliance.',
    icon: Shield,
    slug: 'security-compliance',
    details: 'Achieve and maintain security compliance with our ISO certifications, security audits, and compliance consulting services. Meet regulatory requirements with confidence.',
    features: [
      'ISO 27001 certification',
      'Security audits',
      'Compliance assessments',
      'Risk assessments',
      'Policy development',
      'Training programs',
    ],
    benefits: [
      'Regulatory compliance',
      'Enhanced security posture',
      'Risk mitigation',
      'Customer trust',
      'Competitive advantage',
      'Legal protection',
    ],
    image: '/services/cctv.jpg',
  },
  {
    id: '10',
    title: 'System Configuration',
    description: 'Professional setup and optimization of all IT systems.',
    icon: Settings,
    slug: 'system-configuration',
    details: 'Professional system configuration and optimization services for all your IT infrastructure. We ensure optimal performance, security, and reliability.',
    features: [
      'System optimization',
      'Security hardening',
      'Performance tuning',
      'Software configuration',
      'Network optimization',
      'Monitoring setup',
    ],
    benefits: [
      'Optimal system performance',
      'Enhanced security',
      'Reduced maintenance costs',
      'Improved reliability',
      'Faster troubleshooting',
      'Professional standards',
    ],
    image: '/services/system.jpg',
  },
  {
    id: '11',
    title: 'Data Storage Solutions',
    description: 'NAS and SAN solutions for efficient data management.',
    icon: Database,
    slug: 'data-storage',
    details: 'Enterprise-grade data storage solutions including NAS and SAN systems. Secure, scalable, and high-performance storage for your critical data.',
    features: [
      'Network Attached Storage (NAS)',
      'Storage Area Network (SAN)',
      'RAID configurations',
      'Data deduplication',
      'Snapshot backups',
      'High availability',
    ],
    benefits: [
      'Centralized data management',
      'High performance access',
      'Data protection',
      'Scalable capacity',
      'Cost-effective storage',
      'Business continuity',
    ],
    image: '/services/data.jpg',
  },
  {
    id: '12',
    title: 'Documentation & Support',
    description: 'Comprehensive system documentation and ongoing technical support.',
    icon: FileText,
    slug: 'documentation-support',
    details: 'Complete documentation services and ongoing technical support to ensure your systems remain operational and your team stays informed.',
    features: [
      'System documentation',
      'User manuals',
      'Technical support',
      'Training programs',
      'Help desk services',
      'Maintenance contracts',
    ],
    benefits: [
      'Knowledge transfer',
      'Reduced downtime',
      'Faster issue resolution',
      'Staff empowerment',
      'System reliability',
      'Long-term partnership',
    ],
    image: '/services/documentation.jpg',
  },
  {
    id: '13',
    title: 'DSTV Installation',
    description: 'Professional DSTV installation and setup services.',
    icon: Tv,
    slug: 'dstv-installation',
    details: 'Expert DSTV installation services including dish alignment, cable setup, decoder configuration, and signal optimization for crystal-clear viewing.',
    features: [
      'Professional dish installation',
      'Signal optimization',
      'Multi-room setup',
      'Decoder configuration',
      'Cable management',
      'Warranty included',
    ],
    benefits: [
      'Crystal-clear reception',
      'Professional installation',
      'Extended warranty',
      'Technical support',
      'Multiple viewing options',
      'Entertainment enhancement',
    ],
    image: '/services/dstv.jpg',
  },
  {
    id: '14',
    title: 'Satellite TV',
    description: 'Complete satellite TV solutions and installations.',
    icon: Satellite,
    slug: 'satellite-tv',
    details: 'Comprehensive satellite TV solutions including installation, setup, and maintenance. Access to multiple channels and premium entertainment options.',
    features: [
      'Satellite dish installation',
      'Multiple channel packages',
      'HD and 4K options',
      'Signal amplification',
      'Weather protection',
      'Technical support',
    ],
    benefits: [
      'Wide channel selection',
      'High-quality viewing',
      'Reliable reception',
      'Premium entertainment',
      'Flexible packages',
      'Professional service',
    ],
    image: '/services/satelitte.jpg',
  },
]
